Add pitch range control to preprocess and add postprocess
LeifSulaiman/Music-Style-Transfer pull request #9
Opened 2022-02-02 14:55 UTC by Sebastian-Larsson

Postprocess adds the ability to save a npy file to midi.

2022-02-02 14:57 UTC, LeifSulaiman commented on processing/npy_to_midi_example.py
> +from cgi import test
What is this import used for

2022-02-02 16:19 UTC, LeifSulaiman requested changes
Review changes and add comments in files:

'processing/npy_to_midi__example.py',
'processing/postprocess.py',
'processing/preprocess.py'

2022-02-02 16:19 UTC, LeifSulaiman commented on processing/postprocess.py
> +        song = song.cpu()
I prefer a new line after 'if' statement.

2022-02-02 16:19 UTC, LeifSulaiman commented on processing/postprocess.py
> +    print(song[:-1].shape)
Stray prints, remove this and line 42.

2022-02-02 16:19 UTC, LeifSulaiman commented on processing/postprocess.py
> +    merged_track = pypianoroll.Multitrack(tempo=np.array([bpm], dtype=float))
Why is the resolution not included? Same for line 46.

2022-02-02 16:19 UTC, LeifSulaiman commented on processing/postprocess.py
> +    track : Tensor
Parameter is called song, not track.

2022-02-02 16:19 UTC, LeifSulaiman commented on processing/preprocess.py
> +from turtle import up
Unused import, remove.

2022-02-02 16:19 UTC, LeifSulaiman commented on processing/preprocess.py
> +        If user selects values, the read midi will have a reduced range.
Specify that user must choose range of (>=0, <=127).

2022-02-03 12:25 UTC, Sebastian-Larsson commented on processing/preprocess.py
> +from turtle import up
Done, also removed `pretty_midi as pm` and `json` as they were both unused.

2022-02-03 12:29 UTC, Sebastian-Larsson commented on processing/postprocess.py
> +    merged_track = pypianoroll.Multitrack(tempo=np.array([bpm], dtype=float))
Included in multitrack. Standardtrack doesn't need resolution.

2022-02-03 14:00 UTC, LeifSulaiman approved these changes
Approve changes.

2022-02-03 14:01 UTC, merged